name: Bump Package Version
on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Version bump type'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  bump-version:
    uses: stevezhu/actions/.github/workflows/npm-bump-version.yaml@d59c7bbfb7ec9875d5b3aeb8ad3a1aa59ec346ea # v1
    permissions:
      contents: write
      pull-requests: write
    with:
      version_type: ${{ inputs.version_type }}
