name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  ci:
    uses: stevezhu/actions/.github/workflows/ci-node.yaml@d59c7bbfb7ec9875d5b3aeb8ad3a1aa59ec346ea # v1
